version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: echo "Installing dependencies"
      - run: npm install
      - run: echo "Bundling app for production"
      - run: CI=true npm run build
  test:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: echo "Installing dependencies"
      - run: npm install
      - run: echo "Testing app"
      - run: npm test
workflows:
  version: 2
  general:
    jobs:
      - build
      - test
