version: 2
jobs:
  install:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: echo "Installing dependencies"
      - run: npm install
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: echo "Bundling app for production"
      - run: CI=true npm run build
  test:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: echo "Testing app"
      - run: npm test
  deploy:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: echo "Deploying app to server"
      - run: npm run deploy
workflows:
  version: 2
  pr_workflow:
    jobs:
      - install
      - build:
          requires:
            - install
      - test:
          requires:
            - install
      - deploy:
          requires:
            - install
            - build
